# Generated by Django 3.1.7 on 2021-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Order_or_Date', models.DateField(auto_now_add=True)),
                ('Order_or_Serial', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Bill_or_Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Post', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
